name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on:
      - codebuild-example-selfhosted-github-runner-aws-${{ github.run_id }}-${{ github.run_attempt }}
    services:
      dynamodb:
        image: amazon/dynamodb-local:1.20.0
        ports:
          - "8000:8000"
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -failfast ./... -coverprofile=coverage.txt -covermode=atomic
