name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on:
      - codebuild-example-selfhosted-github-runner-aws-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Run tests
        run: go test -failfast ./... -coverprofile=coverage.txt -covermode=atomic
